export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST";
export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_AUDIO = "GET_AUDIO";
export const GET_AUDIO_REQUEST = "GET_AUDIO_REQUEST";
